# Generated by Django 5.0.1 on 2024-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AIRPORTCODE', models.CharField(max_length=3, unique=True)),
                ('AIRPORTNAME', models.CharField(max_length=255)),
                ('CITYCODE', models.CharField(max_length=3)),
                ('CITYNAME', models.CharField(max_length=255)),
                ('COUNTRYNAME', models.CharField(max_length=255)),
                ('CURRENCYCODE', models.CharField(max_length=3)),
            ],
        ),
    ]
