# Generated by Django 5.0.1 on 2024-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flightclientdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('user_information', models.JSONField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('published_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_flag', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('payed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_no', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_information', models.JSONField(blank=True, null=True)),
                ('payment_information', models.JSONField(blank=True, null=True)),
                ('is_price_changed', models.IntegerField(blank=True, null=True)),
                ('is_cancellation_policy_changed', models.IntegerField(blank=True, null=True)),
                ('is_price_changed_true', models.JSONField(blank=True, null=True)),
                ('is_cancellation_policy_changed_true', models.JSONField(blank=True, null=True)),
                ('changerequestid', models.CharField(blank=True, db_column='ChangeRequestId', max_length=100, null=True)),
                ('cancel_status', models.CharField(blank=True, db_column='Cancel_status', max_length=255, null=True)),
                ('cancellation_details', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('contact_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flightclientdetails',
                'managed': False,
            },
        ),
    ]
