# Generated by Django 4.2.7 on 2024-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelclientdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('user_information', models.JSONField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('published_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_flag', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('payed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_no', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_information', models.JSONField(blank=True, default=dict, null=True)),
                ('payment_information', models.JSONField(blank=True, default=dict, null=True)),
                ('is_price_changed', models.BooleanField(default=False)),
                ('is_cancellation_policy_changed', models.BooleanField(default=False)),
                ('is_price_changed_true', models.JSONField(blank=True, default=dict, null=True)),
                ('is_cancellation_policy_changed_true', models.JSONField(blank=True, default=dict, null=True)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
            options={
                'db_table': 'Hotelclientdetails',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
