# Generated by Django 5.0.1 on 2024-02-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hotelclientdetails_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelclientdetails',
            options={'managed': False},
        ),
    ]
