# Generated by Django 5.0.2 on 2024-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=True)),
                ('description', models.JSONField(blank=True, db_column='Description', null=True)),
                ('tags', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=200, null=True)),
                ('created_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
                ('canonical', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(blank=True, null=True)),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=True)),
                ('description', models.JSONField(blank=True, db_column='Description', null=True)),
                ('tags', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'blog_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('categeory_slug', models.CharField(max_length=50)),
                ('city_id', models.JSONField()),
                ('update_date', models.DateField()),
                ('create_date', models.DateField()),
                ('all_description', models.JSONField()),
                ('updated_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoriesbasedcities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriesname', models.CharField(max_length=255)),
                ('categeory_slug', models.CharField(max_length=255)),
                ('categoriesimage', models.CharField(max_length=255)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'destination_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CcustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('destination', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ccustomer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContinentMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=255)),
                ('description_son', models.JSONField()),
                ('Update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'continent_metas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_category', models.CharField(max_length=255)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_slug', models.CharField(max_length=255)),
                ('canonical', models.CharField(max_length=255)),
                ('destination_title', models.CharField(max_length=255)),
                ('destination_title_slug', models.CharField(max_length=255)),
                ('Tab_image', models.CharField(max_length=255)),
                ('mobile_image', models.CharField(max_length=255)),
                ('updated_name', models.CharField(max_length=255)),
                ('created_name', models.CharField(max_length=255)),
                ('destination_image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metakeyword', models.CharField(max_length=500)),
                ('metatitle', models.CharField(max_length=500)),
                ('metadestination', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'destinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DestinationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=255)),
                ('meta_details', models.JSONField()),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'destination_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FooterHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.JSONField(blank=True, db_column='Header', null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'footer_header',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FooterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_id', models.IntegerField(blank=True, db_column='Header_id', null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'footer_title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(blank=True, null=True)),
                ('create_us', models.DateTimeField(blank=True, null=True)),
                ('update_us', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'homepage_slider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hotel_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternationalAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_city_id', models.IntegerField()),
                ('tour_spot_name', models.CharField(max_length=255)),
                ('tour_spot_slug', models.CharField(max_length=255)),
                ('highlights_content', models.TextField()),
                ('highlights_image', models.TextField()),
                ('includes_content', models.TextField()),
                ('includes_image', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'international_attractions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternationalCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_id', models.IntegerField(blank=True, null=True)),
                ('international_city_name', models.TextField(blank=True, null=True)),
                ('international_city_slug', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'international_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternationalCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_id', models.IntegerField()),
                ('international_city_name', models.CharField(max_length=255)),
                ('international_city_slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'international_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadNumber', models.CharField(max_length=255)),
                ('subTitle', models.CharField(max_length=255)),
                ('packageName', models.CharField(max_length=255)),
                ('placeToVisit', models.CharField(max_length=255)),
                ('itDate', models.DateField()),
                ('itValidDate', models.DateField()),
                ('departureDate', models.DateField()),
                ('numOfNights', models.CharField(max_length=255)),
                ('roomType', models.CharField(max_length=255)),
                ('flight_id', models.CharField(max_length=255)),
                ('costingNotes', models.CharField(blank=True, max_length=255, null=True)),
                ('routeMap', models.CharField(blank=True, max_length=255, null=True)),
                ('termsType', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleType', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_includs', models.TextField()),
                ('pack_excluds', models.TextField()),
                ('payment_poly', models.TextField()),
                ('refound_poly', models.TextField()),
                ('cancle_poly', models.TextField()),
                ('pdf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_json', models.TextField()),
                ('no_need_flight', models.BooleanField(default=False)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('cities_ids', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('Team_Name', models.CharField(max_length=255)),
                ('description', models.JSONField()),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('packages_id', models.CharField(db_column='Packages_id', max_length=255)),
                ('description', models.JSONField(blank=True, null=True)),
                ('homepage', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_category', models.CharField(blank=True, max_length=200, null=True)),
                ('itinaries_id', models.IntegerField()),
                ('category_button', models.BooleanField(default=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagesname', models.CharField(max_length=255)),
                ('description', models.JSONField()),
                ('created_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pages_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadFlight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('pnr_number', models.CharField(max_length=50)),
                ('traveldate', models.DateField(blank=True, null=True)),
                ('returendate', models.DateField(blank=True, null=True)),
                ('baggage', models.CharField(blank=True, max_length=100, null=True)),
                ('ticketattachment', models.CharField(max_length=250)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('uplodername', models.CharField(blank=True, max_length=100, null=True)),
                ('editername', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
                ('flight_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'uploadflight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uploadhotel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, db_column='Hotel_Name', max_length=250, null=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('no_of_nights', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attachment', models.CharField(blank=True, max_length=250, null=True)),
                ('uplotername', models.CharField(blank=True, max_length=100, null=True)),
                ('editername', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploadhotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('traveldate', models.DateField(blank=True, null=True)),
                ('datas', models.JSONField(blank=True, null=True)),
                ('uplodername', models.CharField(blank=True, max_length=100, null=True)),
                ('editername', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploadtransfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadUserdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('tickets', models.JSONField(blank=True, null=True)),
                ('visa', models.JSONField(blank=True, null=True)),
                ('insurense', models.JSONField(blank=True, null=True)),
                ('Passport', models.JSONField(blank=True, null=True)),
                ('uplodername', models.CharField(blank=True, max_length=100, null=True)),
                ('editername', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('updated_by', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploaduserdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_balance', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
            ],
            options={
                'db_table': 'user_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomepageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themename', models.CharField(max_length=255)),
                ('themevalue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'homepagetheme',
            },
        ),
        migrations.CreateModel(
            name='HotelsDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lead_id', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_id', models.CharField(max_length=255)),
                ('HotelOptionNumber', models.CharField(max_length=255)),
                ('hotal_room_type', models.CharField(blank=True, max_length=255, null=True)),
                ('star_ratings', models.CharField(blank=True, max_length=255, null=True)),
                ('hotal_night', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotals_deatils',
            },
        ),
        migrations.CreateModel(
            name='LeadDayInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lead_id', models.IntegerField()),
                ('day', models.TextField()),
                ('country_state_id', models.TextField()),
                ('city_id', models.TextField()),
                ('place_id', models.TextField()),
                ('activities', models.TextField()),
                ('transfers', models.TextField()),
                ('tickets', models.TextField()),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('sorting_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_day_infos',
            },
        ),
        migrations.CreateModel(
            name='LeadDaySightSee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lead_day_id', models.IntegerField()),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_day_sight_sees',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'places',
            },
        ),
    ]
